version: "3"
services:
    telegraf:
        image: telegraf:1.3
        ports:
            - "8125:8125/udp"
        # environment variables and volumes below to
        # allow telegraf in the container to report the host cpu, mem, etc
        environment:
          HOST_PROC: /rootfs/proc
          HOST_SYS: /rootfs/sys
          HOST_ETC: /rootfs/etc
        # or do I want hostname to be telegraf?
        # I think this for the stats to show how I want in influxdb?
        hostname: blargh
        volumes:
            - ./stats/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /sys:/rootfs/sys:ro
            - /proc:/rootfs/proc:ro
            - /etc:/rootfs/etc:ro
    influxdb:
        # influxdb docker config at https://hub.docker.com/_/influxdb/
        image: "influxdb:1.2.4"
        environment:
            - INFLUXDB_GRAPHITE_ENABLED=true
            - INFLUXDB_ADMIN_ENABLED=true
        hostname: influxdb
        volumes:
            - /opt/docker/volumes/influxdb:/var/lib/influxdb
        ports:
            - 8086:8086
            - 2003:2003
            - 8083:8083
        privileged: false
        links:
            - telegraf
    grafana:
        image: "grafana/grafana:4.2.0"
        hostname: grafana
        links:
            - influxdb
        environment:
            - GF_SERVER_ROOT_URL=https://bash-shell.net/grafana/
            - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
            - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
            - GF_SECURITY_USERS_ALLOW_SIGNUP=false
        ports:
            - 3000:3000
        volumes:
            # TODO: permissions/ownership for these volues on the host is mucked up
            # because of how docker volumes work... see if I can make these make sense
            # - ./stats/grafana/etc:/etc/grafana
            - /opt/docker/volumes/grafana/lib:/var/lib/grafana
            - /opt/docker/volumes/grafana/log:/var/log/grafana
volumes:
    influxdb:
