version: "3"
services:
    django:
        image: "registry.gitlab.com/jmichalicek/bash-shell.net:20170827_033036"
        #build:
        #    context: ${BUILD_CONTEXT:-..}
        #    dockerfile: ${DOCKERFILE:-"docker/Dockerfile.dev"}
        #    args:
        #        - PYTHON_VERSION=${PYTHON_VERSION:-3.6.2}
        #        - SHELL=/bin/bash
        stdin_open: true
        tty: true
        user: django
        working_dir: /home/django/bash_shell_net/app
        ports:
            - "127.0.0.1:8000:8000"  # could listen on the docker network ip instead...
        volumes:
            - "${STATIC_FILES_DIR}:/home/django/bash-shell.net/static_collected"
        environment:
            - DOCKER_HOST_ADDR
            - PYTHON_VERSION=3.6.2
            - SHELL=/bin/bash
            - DJANGO_SETTINGS_MODULE
            - DATABASE_URL
            - STATIC_ROOT
            - MEDIA_ROOT
            - REDIS_HOST
            - PYTHONIOENCODING=utf8
            - LC_ALL=en_US.UTF-8
        #command: /home/django/.pyenv/versions/bash-shell-net/bin/gunicorn --workers 2 --bind 0.0.0.0:8000 --name django --max-requests=1000 bash_shell_net.wsgi:application
        #command: ['bash', '-c', '/home/django/.pyenv/versions/bash-shell-net/bin/gunicorn', '--workers', '2', '--bind', '0.0.0.0:8000', '--name', 'django', '--max-requests=1000', 'bash_shell_net.wsgi:application']
        extra_hosts:
            - "database:$DOCKER_HOST_ADDR"
        deploy:
            resources:
                limits:
                    memory: 100m
                reservations:
                    memory: 50m
volumes:
    static_files:
